fixtures:
  forge_modules:
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.6.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.2.4'
    git:
      repo: 'puppetlabs/git'
      ref: '0.4.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.9.0'
    vcsrepo:
      repo: 'puppetlabs/vcsrepo'
      ref: '1.3.1'
  symlinks:
    kibana3: "#{source_dir}"
