---
notifications:
  email:
    - alejandro@ideasftw.com
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.6
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.2.0"
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.3.0"
